MVC/NorthwindSolution/Northwind.Web/Models/Employee.cs
namespace Northwind.Web.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime BirthDate { get; set; }
    }
}

MVC/NorthwindSolution/Northwind.Web/Models/ErrorViewModel.cs
namespace Northwind.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/NorthwindSolution/Northwind.Web/Controllers/EmployeeController.cs
 using Microsoft.AspNetCore.Mvc;
using Northwind.Web.Models;
using Northwind.Web.Repository;

namespace Northwind.Web.Controllers
{
    public class EmployeeController : Controller
    {
        // use dependency injection
        private readonly IEmployee _IEmployee;


        public EmployeeController(IEmployee iEmployee)
        {
            _IEmployee = iEmployee;
        }

        public IActionResult ListEmployee()
        {
           /* var listOfEmployee = new List<Employee>
            {
                new Employee {Id=1001,Name="Kang Dian", BirthDate = new DateTime(2000,12,01)},
                new Employee {Id=1001,Name="Celine", BirthDate = new DateTime(2001,01,12)},
                new Employee {Id=1001,Name="Arya", BirthDate = new DateTime(2002,10,18)}
            };*/ 
             return View("ListEmployee", _IEmployee.GetAll());
        }

        public IActionResult Category()
        {
            return View();
        }
    }
}

MVC/NorthwindSolution/Northwind.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Northwind.Web.Models;
using System.Diagnostics;

namespace Northwind.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var myName = "Kang Dian";
            return View("Index", myName);
        }

        public IActionResult Privacy()
        {
            var hour = DateTime.Now.Hour;
            var greeting = hour > 12 ? "Good Day" : "Good Morning";
            return View("Privacy",greeting);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/NorthwindSolution/Northwind.Web/Views/Employee/Category.cshtml
<h3> List Categories</h3>

MVC/NorthwindSolution/Northwind.Web/Views/Employee/ListEmployee.cshtml
@model List<Employee>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div>
    <h3>List of Employee</h3>
   @* @foreach (var item in @Model)
    {
       @* <ul>
            <li>
                @item.Id @item.Name @item.BirthDate
            </li>
        </ul>

    }*@
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">FullName</th>
                    <th scope="col">Birth Date</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.BirthDate</td>
                    </tr>
                
                }
            </tbody>

        </table>
        
</div>

MVC/NorthwindSolution/Northwind.Web/Views/Home/Index.cshtml
@model string;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    @*<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@
    <p>Hello, @Model</p>
    <p>Say, @Model</p>
</div>

MVC/NorthwindSolution/Northwind.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Northwind.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Northwind.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Northwind.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="ListEmployee">Employee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Northwind.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>